[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.init]
dependencies = ["install-rust-src"]

[tasks.build-release]
command = "cargo"
args = ["xbuild", "--target", "armv5te-nspire-eabi.json", "--release"]

[tasks.build]
command = "cargo"
args = ["xbuild", "--target", "armv5te-nspire-eabi.json"]

[tasks.dev]
dependencies = ["build"]
script = [
'''
NAME="$CARGO_MAKE_CRATE_NAME"
TARGET_DIR="$(cargo metadata --format-version 1 | jq -r '.target_directory')"
TARGET=armv5te-nspire-eabi
MANIFEST="$(cargo read-manifest)"
FRIENDLY_NAME="$(jq -r '.metadata.zehn.name' <<< "$MANIFEST" )"
COMPRESS="$(jq -r '.metadata.zehn.compress' <<< "$MANIFEST" )"
FLAGS=""
[ "$COMPRESS" = "true" ] && FLAGS="$FLAGS --compress"
[ "FRIENDLY_NAME" != "null" ] && FLAGS="$FLAGS --name \"$FRIENDLY_NAME\""
genzehn --input "$TARGET_DIR/$TARGET/debug/$NAME" --output "$TARGET_DIR/$TARGET/debug/$NAME.zehn" $FLAGS
make-prg "$TARGET_DIR/$TARGET/debug/$NAME.zehn" "$TARGET_DIR/$TARGET/debug/$NAME.tns"
'''
]

[tasks.release]
dependencies = ["build-release"]
script = [
'''
NAME="$CARGO_MAKE_CRATE_NAME"
TARGET_DIR="$(cargo metadata --format-version 1 | jq -r '.target_directory')"
TARGET=armv5te-nspire-eabi
MANIFEST="$(cargo read-manifest)"
FRIENDLY_NAME="$(jq -r '.metadata.zehn.name' <<< "$MANIFEST" )"
COMPRESS="$(jq -r '.metadata.zehn.compress' <<< "$MANIFEST" )"
FLAGS=""
[ "$COMPRESS" = "true" ] && FLAGS="$FLAGS --compress"
[ "FRIENDLY_NAME" != "null" ] && FLAGS="$FLAGS --name \"$FRIENDLY_NAME\""
genzehn --input "$TARGET_DIR/$TARGET/release/$NAME" --output "$TARGET_DIR/$TARGET/release/$NAME.zehn" $FLAGS
make-prg "$TARGET_DIR/$TARGET/release/$NAME.zehn" "$TARGET_DIR/$TARGET/release/$NAME.tns"
'''
]
